### ISSUE TITLE
使用helm 部署的2 shards 1 replica 的群集为什么不用on cluster 在节点1上建库建表就会自动同步到节点2

### ISSUE THREAD

**Issue by yoke88** [radondb/radondb-clickhouse-kubernetes#19]
1. 环境是在minikube 下。用Helm的方式部署了clickhouse-operator 以及clickhouse-cluster (helm 地址https://radondb.github.io/radondb-clickhouse-kubernetes/）
2. 创建群集的values.yaml 如下：
``` yaml
---
clickhouse:
  user: [{"username": "clickhouse", "password": "c1ickh0use0perator", "networks": ["127.0.0.1", "0.0.0.0/0"]}]
  replicascount: 1
  shardscount: 2
  clusterName: cluster1
zookeeper:
  replicas: 1

```
3. 部署之后，连接到节点1 执行create database test;
4. 在节点2上执行show databases,能看到test数据库，在节点1上也能看到test数据库，如果执行建表语句（不使用on cluster 语句），建的表也会在另外一个节点上看到，但是数据不会同步。
5. 如果执行删除库、删除表，也会在其他节点同步。

建议文档中能否增加对分布式表建表、对分布式复制表的建表和使用举例。感觉上面的行为和目前找到的文档中描述的不一致，到底是我的环境有问题还是额外有了什么改进我不知道呢。

另外radondb 社区在哪里可以进行交流呢？
